### ISSUE TITLE
I love it!!!

### ISSUE THREAD

**Issue by jackey-jiang** [kiran-venugopal/lofi-fm#1]
I really like this project. It's very good. But I have one comment, when I listen to a song, I don't know the name of the song that's playing now. So, if I could add the name of the song that is currently playing, I think it would be perfect, so if there is a good song, I can find it

**Comment by kiran-venugopal** [comment]
Thank you! Glad to hear that you are enjoying Lofi FM 💜

Currently Youtube API doesn't have this support of getting the video fragment name, so I dont see  a solution for this right now. If you have found a fix feel free to make PR or comment about it.

**Comment by jackey-jiang** [comment]
Figure 1 shows the youtube live screen with the name of the song in the top left corner. But picture 2 is your playback page does not show the youtube screen in full screen, can you fix it and update it? Thank you very much. This way I can see the song that was live. I'm very sorry, I'm Chinese and my English is not very good, so please excuse me.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/10288803/174943733-acddf3b6-ef42-48db-b59a-4af3319bf489.png">

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/10288803/174944196-c24d6fa4-3e93-4907-bfde-1dacee86823e.png">

**Comment by kiran-venugopal** [comment]
Yes, currently the background video size is bit scaled to hide the youtube controls. So the solution will be adding a button to disable that scaling so that you can see the video in original height and width. I will update the app during this weekend 👍

**Comment by jackey-jiang** [comment]
> Yes, currently the background video size is bit scaled to hide the youtube controls. So the solution will be adding a button to disable that scaling so that you can see the video in original height and width. I will update the app during this weekend 👍

Thank you! 💯 :)

**Comment by kiran-venugopal** [comment]
@jackey-jiang  Hi. i have added a toggle button to disable / enable the scaling. 👍 let me know if you found any issues 
![lofi-fm-scale-disabled](https://user-images.githubusercontent.com/62516337/175765541-23a57578-007b-47f3-81fe-d7d08161fff9.PNG)
