### ISSUE TITLE
Web App displays a white screen

### ISSUE THREAD

**Issue by clarkissac** [kiran-venugopal/lofi-fm#8]
Let me start by saying that I love your app. I have been using it for hours every day for like the past year or so. But it suddenly stopped working today and I only get a white blank screen on the website. I tried it on 3 different browsers and my phone too, without success.
There are also some Type Errors in the dev console.

**Comment by kiran-venugopal** [comment]
Hi @clarkissac , thanks for reaching out and glad to hear you are loving Lofi FM 🩷

The app was down due to some of the unexpected changes from youtube's APIs, i have pushed some changes and right now the app should be working for you 
Feel free to comment here if you are facing issues

**Comment by clarkissac** [comment]
cool thanks for the quick fix :D
